### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-thailand#309]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] currency_rate_update_TH_BOT - By @Saran440 - #391
- [x] l10n_th_account_asset_management - By @Saran440 - #423
- [x] l10n_th_account_tax - By @Saran440 - #394
- [x] l10n_th_account_tax_expense - By @Saran440 - #397
- [x] l10n_th_account_tax_multi - By @Saran440 - #401
- [x] l10n_th_account_tax_report - By @Saran440 - #398
- [x] l10n_th_account_wht_cert_form - By @Saran440 - #400
- [x] l10n_th_amount_to_text - By @Saran440 - #315
- [x] l10n_th_bank_payment_export - By @Saran440 - #425
- [x] l10n_th_base_location - By @Saran440 - #389
- [x] l10n_th_base_sequence - By @Pani-k-folk - #466
- [x] l10n_th_fonts - By @amincheloh - #319
- [ ] l10n_th_gov_account_asset_management - By @Saran440 - #474
- [x] l10n_th_gov_purchase_agreement - By @Saran440 - #473
- [x] l10n_th_mis_report - By @Saran440 - #428
- [ ] l10n_th_multicurrency_revaluation - By @Saran440 - #416
- [x] l10n_th_partner - By @Saran440 - #390
- [x] l10n_th_promptpay - By @TITUS6304658 - #378
- [x] l10n_th_tier_department - By @Saran440 - #429
- [x] l10n_th_tier_department_demo - By @Saran440 - #429

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
