### ISSUE TITLE
Localization Roadmap (ecosoft)

### ISSUE THREAD

**Issue by kittiu** [OCA/l10n-thailand#35]
## Financial Statement

- [ ] TB (1,2,3,4,5,...)
- [ ] BS (1 = 2+3) - @Saran440 (mis_builder + l10n_th as CoA)
- [ ] PL (4 – 5+6+...) - @Saran440 (mis_builder + l10n_th as CoA)
  * CC
  * PC
  * Project
- [ ] Change in Equity (3 = Captial + (R/E or Deficit)
- [ ] NTF (open items helps to NTF and BS detail)
- [ ] Cashflow statement (for listed company and Public company)
- [ ] GL
- [ ] Bank statement - @Saran440 (discuss with Bow)
- [ ] Partner ledger
- [ ] Ratio report

## Stock

- [ ] Stock card (Bin card) - @ps-tubtim https://github.com/OCA/stock-logistics-reporting/pull/69
- [ ] Stock valuation report - @ps-tubtim

## VAT

- [ ] VAT Report - @ps-tubtim 
- [ ] PP30

## WHT

- [ ] PND 3, 53 (cover + attachment) - @kongrattapong
- [ ] PND 1,2 (HR – payroll)
- [ ] PND 51 (mid-year Tax return – P/L)
- [ ] PND 50 (Annaul Tax return – BS and PL)
